# Generated by Django 3.0.4 on 2020-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200319_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
