# Generated by Django 3.0.4 on 2020-03-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingridient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='ingridient',
            name='meal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Meal'),
            preserve_default=False,
        ),
    ]
