# Generated by Django 3.0.4 on 2020-03-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200319_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='meal_id',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingridients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Ingridient'),
            preserve_default=False,
        ),
    ]
