# Generated by Django 3.0.4 on 2020-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200320_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingridients',
            field=models.ManyToManyField(to='api.Ingridient'),
        ),
    ]
