# Generated by Django 3.0.4 on 2020-03-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200320_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient', to='api.Product'),
        ),
    ]
